package middleware

import (
	"log/slog"
	"net/http"
	"time"
)

// responseWriterWrapperLogging intercepts the HTTP status so we can log the correct response code.
type responseWriterWrapperLogging struct {
	http.ResponseWriter
	statusCode int
}

func (w *responseWriterWrapperLogging) WriteHeader(statusCode int) {
	w.statusCode = statusCode
	w.ResponseWriter.WriteHeader(statusCode)
}

// Logging is an HTTP middleware that logs each request, equivalent to gRPC's LoggingInterceptor.
func Logging(log *slog.Logger) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			start := time.Now()

			// Wrapper to capture the HTTP status generated by the handler.
			ww := &responseWriterWrapperLogging{
				ResponseWriter: w,
				statusCode:     http.StatusOK, // Default from net/http if WriteHeader is not called explicitly.
			}

			// Executes the next handler in the chain.
			next.ServeHTTP(ww, r)

			duration := time.Since(start)

			attrs := []any{
				slog.String("method", r.Method),
				slog.String("path", r.URL.Path),
				slog.Int("status_code", ww.statusCode),
				slog.String("duration", duration.String()),
			}

			// Severity mapping based on the HTTP status code (analogous to gRPC codes).
			switch {
			case ww.statusCode >= http.StatusInternalServerError: // 5xx: Server Errors (Internal, Unavailable, etc.)
				log.ErrorContext(r.Context(), "HTTP request failed", attrs...)
			case ww.statusCode >= http.StatusBadRequest: // 4xx: Client Errors (InvalidArgument, NotFound, etc.)
				log.WarnContext(r.Context(), "HTTP request rejected", attrs...)
			default: // 2xx / 3xx: Success or Redirection
				log.InfoContext(r.Context(), "HTTP request completed", attrs...)
			}
		})
	}
}
