package middleware

import (
	"net/http"
	"time"

	"github.com/andreis3/isura-ledger-ms/internal/application"
)

type responseWriterWrapperMetrics struct {
	http.ResponseWriter
	statusCode int
}

// MetricsMiddleware is an HTTP middleware that records request metrics, equivalent to gRPC's MetricsInterceptor.
func MetricsMiddleware(metrics application.Metrics) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			start := time.Now()

			// Wrapper to capture the HTTP status generated by the handler.
			ww := &responseWriterWrapperMetrics{
				ResponseWriter: w,
				statusCode:     http.StatusOK, // Default from net/http if WriteHeader is not called explicitly.
			}

			// Executes the next handler in the chain.
			next.ServeHTTP(ww, r)

			duration := float64(time.Since(start).Milliseconds())
			statusCode := ww.statusCode

			// We use the pattern r.Method + " " + r.URL.Path (or r.Pattern if using Go 1.22+ native routing)
			// as the route identifier, analogous to gRPC's info.FullMethod.
			routeIdentifier := r.Method + " " + r.URL.Path

			metrics.RecordRequestTotal(routeIdentifier, "http", statusCode)
			metrics.RecordRequestDuration(routeIdentifier, "http", statusCode, duration)
		})

	}
}
